stages:
  clean_and_split:
    cmd: python news_cat/ml/clean_data.py
    deps:
    - data/raw_data.csv
    - news_cat/ml/clean_data.py
    outs:
    - artifacts/lbl_encoder.jlib
    - data/raw_data.feather
    - data/test_df.feather
    - data/train_df.feather
    - data/valid_df.feather
