stages:
  clean_and_split:
    cmd: python news_cat/ml/clean_data.py
    deps:
    - data/raw_data.csv
    - news_cat/ml/clean_data.py
    outs:
    - artifacts/lbl_encoder.jlib
    - data/raw_data.feather
    - data/test_df.feather
    - data/train_df.feather
    - data/valid_df.feather
  embed_tfidf:
    cmd: python scripts/train_tfidf.py
    deps:
    - data/test_df.feather
    - data/train_df.feather
    - data/valid_df.feather
    - scripts/train_tfidf.py
    outs:
    - artifacts/tfidf.jlib
    - data/test_lbl.npy
    - data/test_tfidf.npz
    - data/train_lbl.npy
    - data/train_tfidf.npz
    - data/valid_lbl.npy
    - data/valid_tfidf.npz
